[network]

# Expose your server here to query the scanner for your utxos
# Default: 127.0.0.1:8080
expose_http = "localhost:8888"

# Indexing server for silent payments that follows the blindbit standard
# Default: "http://localhost:8000"
blindbit_server = "http://localhost:8000"

# The address of the Electrum server to connect to.
# Keep this empty to not use electrum at all. 
# UTXO states will be set to spent or unspent and spent_unconfirmed will only be tracked locally in one daemon instance.
# Using a public or not trusted Electrum server will leak privacy.
electrum_server = "localhost:50000"

# Should the electrum server be accessed via tor
# Default: true
electrum_tor = true

# Set the proxy host through which tor should be accessed. Normally it's 127.0.0.1:9050
# Default: 127.0.0.1:9050
electrum_tor_proxy_host = "127.0.0.1:9050"

# Defines on which chain the wallet runs. Allowed values: main, test, signet, regtest.
# Default: signet
chain = "signet"

[auth]
# set the user name for basic auth
user = "<user-name>"

# set the password for basic auth
pass = "<your-strong-password>"

[wallet]

# Your public spend key <33-byte compressed>
spend_pub_key = "<spend_pub_key>"

# The secret scan key. THis key is needed to find transactions where you receive funds. Sending is not possible using this key.
# <32-byte secret/private key>
scan_secret_key = "<scan_secret_key>"

# The wallet will only request tweaks for transactions where the utxo with the largest value exceeds the `dust_limit` value.
# Note that if you receive funds below this threshold you might not find them. Rescan without a dustlimit to find those.
# default = 1000
dust_limit = 1000

# The number of labels that should be checked during scanning. For now this number has to be defined here and can't be changed at runtime. 
# NOTE: Setting this number higher than necessary comes with a lot of computational costs. The scan times increase a lot when scaling labels. Test it and reduce if needed.
label_count = 21

# when the wallet was created. The scanner will not scan anything from before that blockheight
birth_height = 840000
